services:
  - type: web
    name: fraud-detection-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn fraud_api:app"
    envVars:
      - key: SHOPIFY_API_KEY
        value: bf520678d939baaf977cf4fbc5a00ba1
      - key: SHOPIFY_PASSWORD
        value: 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
      - key: SHOPIFY_STORE
        value: nerdused.myshopify.com
      - key: PYTHON_VERSION
        value: 3.10
